= OBS Installation Instructions
Benjamin Shearlock <bcs@juxt.pro>
v1.0, 2024-10-28
:status: WORKING RECOMMENDATION
:classification: INTERNAL
:reader-nickname: User
:reader-code: <juxter-code>
:reader-fullname: User
:toc: macro

== Introduction

Welcome {reader-nickname}

=== Objective

To document the steps to install and configure OBS Studio for streaming and/or recording using the pre-configured JUXT OBS setup.

toc::[]

=== Audience

This document is intended for users who are setting up OBS Studio for the first time. It will help them configure it with the JUXT OBS package.

== Procedure

=== Requirements

* OBS Studio Installer
* JUXT OBS configuration package (JUXT-OBS.zip)

=== OBS Installation and Setup

==== Step 1: Download and Extract the JUXT OBS Package

Download the JUXT OBS configuration package [link:OBS-JUXT.zip[Download OBS-JUXT.zip]] and extract/unzip it to a convenient location on your system.

==== Step 2: Install OBS Studio

Go to this link: https://obsproject.com/ and download the appropriate installer for your operating system. Alternatively, you could also install OBS from your system's "App Store", or via a package manager.

Install OBS Studio following the usual installation process for your system.

